#!/usr/bin/env python3
"""Exact regression certificate for N5-RS-P5 / HC-DU-054.

The analytic result lives in:
  explorations/cross-arena-dynamic-sufficiency-and-formation-non-unification-2026-07-27.md

This is not a physical simulation or a new theorem engine. It preserves the
finite witnesses behind two different fibre tests:

* antecedent selection acts on complete implementation/interface variants;
* dynamic sufficiency acts on states or histories after one interface is
  fixed;
* the gravitational-wave and metastable specimens pass the same restricted
  transfer test and fail after capability enlargement; and
* neither frozen antecedent selects its complete accessible formed interface.
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path
from typing import Callable, Hashable, Sequence, TypeVar


ROOT = Path(__file__).resolve().parents[1]
ARTIFACT = (
    ROOT
    / "tests"
    / "artifacts"
    / "du_cross_arena_dynamic_sufficiency_result.json"
)

T = TypeVar("T")
CHECKS: list[dict[str, object]] = []


def record(name: str, passed: bool, detail: object) -> None:
    CHECKS.append({"name": name, "passed": bool(passed), "detail": detail})


def factorizes(
    domain: Sequence[T],
    source: Callable[[T], Hashable],
    target: Callable[[T], Hashable],
) -> bool:
    decoder: dict[Hashable, Hashable] = {}
    for item in domain:
        key = source(item)
        value = target(item)
        if key in decoder and decoder[key] != value:
            return False
        decoder[key] = value
    return True


def kernel(
    domain: Sequence[T],
    statistic: Callable[[T], Hashable],
) -> frozenset[tuple[int, int]]:
    return frozenset(
        (left, right)
        for left in range(len(domain))
        for right in range(len(domain))
        if statistic(domain[left]) == statistic(domain[right])
    )


def join_partition(
    domain: Sequence[T],
    statistics: Sequence[Callable[[T], Hashable]],
) -> tuple[tuple[int, ...], ...]:
    """Partition generated by the join of the statistics' kernels."""

    parent = list(range(len(domain)))

    def find(index: int) -> int:
        while parent[index] != index:
            parent[index] = parent[parent[index]]
            index = parent[index]
        return index

    def union(left: int, right: int) -> None:
        left_root = find(left)
        right_root = find(right)
        if left_root != right_root:
            parent[right_root] = left_root

    for statistic in statistics:
        buckets: dict[Hashable, list[int]] = {}
        for index, item in enumerate(domain):
            buckets.setdefault(statistic(item), []).append(index)
        for bucket in buckets.values():
            for index in bucket[1:]:
                union(bucket[0], index)

    blocks: dict[int, list[int]] = {}
    for index in range(len(domain)):
        blocks.setdefault(find(index), []).append(index)
    return tuple(sorted(tuple(block) for block in blocks.values()))


def partition_from(
    domain: Sequence[T],
    statistic: Callable[[T], Hashable],
) -> tuple[tuple[int, ...], ...]:
    buckets: dict[Hashable, list[int]] = {}
    for index, item in enumerate(domain):
        buckets.setdefault(statistic(item), []).append(index)
    return tuple(sorted(tuple(block) for block in buckets.values()))


def matvec(
    matrix: tuple[tuple[Fraction, Fraction], tuple[Fraction, Fraction]],
    vector: tuple[Fraction, Fraction],
) -> tuple[Fraction, Fraction]:
    return (
        matrix[0][0] * vector[0] + matrix[0][1] * vector[1],
        matrix[1][0] * vector[0] + matrix[1][1] * vector[1],
    )


def matmul(
    left: tuple[tuple[Fraction, Fraction], tuple[Fraction, Fraction]],
    right: tuple[tuple[Fraction, Fraction], tuple[Fraction, Fraction]],
) -> tuple[tuple[Fraction, Fraction], tuple[Fraction, Fraction]]:
    return (
        (
            left[0][0] * right[0][0] + left[0][1] * right[1][0],
            left[0][0] * right[0][1] + left[0][1] * right[1][1],
        ),
        (
            left[1][0] * right[0][0] + left[1][1] * right[1][0],
            left[1][0] * right[0][1] + left[1][1] * right[1][1],
        ),
    )


def norm_squared(vector: tuple[Fraction, Fraction]) -> Fraction:
    return vector[0] ** 2 + vector[1] ** 2


@dataclass(frozen=True)
class GWImplementation:
    archive_route: str


@dataclass(frozen=True)
class History:
    length: int
    word: str
    endpoint: str


@dataclass(frozen=True)
class HostImplementation:
    archive_route: str


NEXT_STATE = {"x0": "x1", "x1": "x2", "x2": "x3", "x3": "x0"}
EDGE_KIND = {"x0": "W", "x1": "C", "x2": "W", "x3": "C"}


def build_histories(max_length: int) -> tuple[History, ...]:
    state = "x1"
    word = ""
    histories = [History(0, word, state)]
    for length in range(1, max_length + 1):
        word += EDGE_KIND[state]
        state = NEXT_STATE[state]
        histories.append(History(length, word, state))
    return tuple(histories)


def erasure_support_is_exact(
    domain: Sequence[T],
    record_map: Callable[[T], Hashable],
    target: Callable[[T], Hashable],
    reveal_probability: Fraction,
) -> bool:
    """Support-level exactness of reveal-or-erase access."""

    observations: list[tuple[T, Hashable]] = []
    for item in domain:
        if reveal_probability > 0:
            observations.append((item, ("revealed", record_map(item))))
        if reveal_probability < 1:
            observations.append((item, ("erased",)))
    return factorizes(
        observations,
        lambda observation: observation[1],
        lambda observation: target(observation[0]),
    )


def main() -> int:
    rotation = (
        (Fraction(3, 5), Fraction(4, 5)),
        (Fraction(-4, 5), Fraction(3, 5)),
    )
    refined_rotation = matmul(rotation, rotation)
    values = (Fraction(-1), Fraction(0), Fraction(1))
    gw_states = tuple((plus, cross) for plus in values for cross in values)

    gw_intensity = norm_squared
    gw_future_intensity = lambda state: norm_squared(matvec(rotation, state))
    gw_oriented = lambda state: matvec(rotation, state)[0]
    gw_visible_record = gw_intensity
    gw_hidden_record = lambda state: "blank"
    gw_full_archive = lambda state: state

    record(
        "gw_supplied_intensity_record_transfers",
        factorizes(gw_states, gw_visible_record, gw_future_intensity),
        "decoder(q)=q under the frozen orthogonal transport",
    )
    record(
        "gw_supplied_intensity_record_is_noninjective",
        len(partition_from(gw_states, gw_visible_record)) < len(gw_states),
        {
            "state_count": len(gw_states),
            "record_blocks": len(partition_from(gw_states, gw_visible_record)),
        },
    )
    record(
        "gw_capability_enlargement_reopens_record",
        not factorizes(gw_states, gw_visible_record, gw_oriented),
        "same intensity can have different oriented response",
    )
    record(
        "gw_orthogonal_subdivision_preserves_intensity_transfer",
        all(
            norm_squared(matvec(refined_rotation, state)) == norm_squared(state)
            for state in gw_states
        ),
        "two exact rational orthogonal steps",
    )
    record(
        "gw_full_two_component_archive_is_injective",
        len(partition_from(gw_states, gw_full_archive)) == len(gw_states),
        {"rank_type": "two_component_tomography"},
    )

    gw_implementations = (
        GWImplementation("accessible_A"),
        GWImplementation("hidden_H"),
    )
    gw_antecedent = lambda implementation: (
        "same_GR_packet_transport",
        "same_probe_response",
    )
    gw_interface = lambda implementation: implementation.archive_route
    record(
        "gw_antecedent_does_not_select_archive_access",
        not factorizes(gw_implementations, gw_antecedent, gw_interface),
        "same packet/probe antecedent, accessible-versus-hidden archive routing",
    )

    gw_common_partition = join_partition(
        gw_states,
        (gw_visible_record, gw_hidden_record),
    )
    record(
        "gw_antecedent_guaranteed_operational_quotient_is_trivial",
        len(gw_common_partition) == 1,
        {"blocks": [list(block) for block in gw_common_partition]},
    )
    record(
        "gw_nonconstant_intensity_is_not_antecedent_robust",
        not factorizes(gw_states, gw_hidden_record, gw_future_intensity),
        "hidden archive arm leaves the nonconstant target unresolved",
    )

    histories = build_histories(8)
    host_endpoint = lambda history: history.endpoint
    host_next = lambda history: NEXT_STATE[history.endpoint]
    host_occurrence = lambda history: int("W" in history.word)
    host_visible_record = lambda history: (
        history.endpoint,
        f"token:{history.word}",
    )
    host_hidden_record = lambda history: (history.endpoint, "blank")
    host_full_archive = lambda history: (
        history.endpoint,
        f"token:{history.word}",
    )

    record(
        "host_endpoint_transfers_next_reduced_law",
        factorizes(histories, host_endpoint, host_next),
        "ordinary Markov operational closure",
    )
    record(
        "host_endpoint_is_noninjective",
        len(partition_from(histories, host_endpoint)) < len(histories),
        {
            "history_count": len(histories),
            "endpoint_blocks": len(partition_from(histories, host_endpoint)),
        },
    )
    record(
        "host_occurrence_capability_reopens_endpoint",
        not factorizes(histories, host_endpoint, host_occurrence),
        {"witness_lengths": [0, 4]},
    )
    record(
        "host_full_history_archive_is_injective",
        len(partition_from(histories, host_full_archive)) == len(histories),
        {"history_count": len(histories)},
    )

    host_implementations = (
        HostImplementation("accessible_A"),
        HostImplementation("hidden_H"),
    )
    host_antecedent = lambda implementation: (
        tuple(sorted(NEXT_STATE.items())),
        tuple(sorted(EDGE_KIND.items())),
    )
    host_interface = lambda implementation: implementation.archive_route
    record(
        "host_antecedent_does_not_select_archive_access",
        not factorizes(host_implementations, host_antecedent, host_interface),
        "same generator, accessible-versus-hidden archive routing",
    )

    host_common_partition = join_partition(
        histories,
        (host_visible_record, host_hidden_record),
    )
    endpoint_partition = partition_from(histories, host_endpoint)
    record(
        "host_antecedent_guaranteed_quotient_is_endpoint",
        host_common_partition == endpoint_partition,
        {"blocks": [list(block) for block in host_common_partition]},
    )
    record(
        "host_next_target_is_antecedent_robust",
        factorizes(histories, host_hidden_record, host_next),
        "next reduced state factors through every admitted native record",
    )
    record(
        "host_history_target_is_not_antecedent_robust",
        not factorizes(histories, host_hidden_record, host_occurrence),
        "occurrence fails through the finest completion-common quotient",
    )

    opaque_history = lambda history: (
        history.endpoint,
        f"opaque:{1000 + history.length}",
    )
    record(
        "lossless_relabeling_preserves_host_record_kernel",
        kernel(histories, host_visible_record) == kernel(histories, opaque_history),
        "token spelling does not change the quotient",
    )
    encoded_intensity = lambda state: f"q:{gw_intensity(state)}"
    record(
        "lossless_relabeling_preserves_gw_record_kernel",
        kernel(gw_states, gw_visible_record) == kernel(gw_states, encoded_intensity),
        "scalar encoding does not change the quotient",
    )

    host_pair = (histories[0], histories[4])
    gw_pair = ((Fraction(0), Fraction(0)), (Fraction(1), Fraction(0)))
    record(
        "partial_erasure_cannot_restore_exact_host_history_sufficiency",
        not erasure_support_is_exact(
            host_pair,
            host_visible_record,
            host_occurrence,
            Fraction(1, 2),
        )
        and erasure_support_is_exact(
            host_pair,
            host_visible_record,
            host_occurrence,
            Fraction(1),
        ),
        "exactness returns only at complete revelation for the witness pair",
    )
    record(
        "partial_erasure_cannot_restore_exact_gw_intensity_sufficiency",
        not erasure_support_is_exact(
            gw_pair,
            gw_visible_record,
            gw_future_intensity,
            Fraction(1, 2),
        )
        and erasure_support_is_exact(
            gw_pair,
            gw_visible_record,
            gw_future_intensity,
            Fraction(1),
        ),
        "exactness returns only at complete revelation for the witness pair",
    )

    host_resource_bits_8 = math.ceil(math.log2(len(histories)))
    host_resource_bits_40 = math.ceil(math.log2(41))
    record(
        "host_history_tomography_resource_grows_with_horizon",
        host_resource_bits_40 > host_resource_bits_8,
        {
            "prefix_9_minimum_bits": host_resource_bits_8,
            "prefix_41_minimum_bits": host_resource_bits_40,
        },
    )
    gw_resource_index = {
        "carrier_type": "continuous_two_component_vector",
        "component_count": 2,
        "requires_precision_contract": True,
    }
    host_resource_index = {
        "carrier_type": "finite_history_prefix",
        "prefix_count": 41,
        "minimum_bits": host_resource_bits_40,
    }
    record(
        "gw_and_host_resource_indices_are_not_one_scalar",
        (
            gw_resource_index["carrier_type"]
            != host_resource_index["carrier_type"]
            and gw_resource_index["requires_precision_contract"]
            and host_resource_index["minimum_bits"] == math.ceil(math.log2(41))
        ),
        {
            "gw_exact_control": gw_resource_index,
            "host_exact_control": host_resource_index,
            "verdict": "NO_CROSS_ARENA_RESOURCE_SCALAR_WITHOUT_RETYPING",
        },
    )

    # The two fibre conditions are logically independent. Each control below
    # has its own implementation-fibre maps (a, xi) and state-fibre maps
    # (r, t), and the four controls realize all truth-value combinations.
    binary = (0, 1)
    identity = lambda value: value
    constant = lambda value: 0
    independence_controls = {
        "selected_and_transfer": (
            factorizes(binary, identity, identity),
            factorizes(binary, identity, identity),
        ),
        "selected_and_failure": (
            factorizes(binary, identity, identity),
            factorizes(binary, constant, identity),
        ),
        "unselected_and_transfer": (
            factorizes(binary, constant, identity),
            factorizes(binary, identity, identity),
        ),
        "unselected_and_failure": (
            factorizes(binary, constant, identity),
            factorizes(binary, constant, identity),
        ),
    }
    truth_table = set(independence_controls.values())
    record(
        "selection_and_transfer_are_logically_independent",
        truth_table
        == {(True, True), (True, False), (False, True), (False, False)},
        {
            name: list(result)
            for name, result in independence_controls.items()
        },
    )
    record(
        "both_arenas_share_unselected_interface_plus_restricted_transfer",
        (
            factorizes(gw_states, gw_visible_record, gw_future_intensity)
            and factorizes(histories, host_endpoint, host_next)
            and not factorizes(gw_implementations, gw_antecedent, gw_interface)
            and not factorizes(
                host_implementations,
                host_antecedent,
                host_interface,
            )
        ),
        "same operational shadow; different native physical implementations",
    )
    record(
        "both_arenas_fail_after_capability_growth",
        (
            not factorizes(gw_states, gw_visible_record, gw_oriented)
            and not factorizes(histories, host_endpoint, host_occurrence)
        ),
        "orientation and occurrence are distinct arena-native first leaks",
    )
    record(
        "full_repairs_are_tomographic_not_compressive",
        (
            len(partition_from(gw_states, gw_full_archive)) == len(gw_states)
            and len(partition_from(histories, host_full_archive))
            == len(histories)
        ),
        "both repairs identify every admitted finite specimen",
    )

    passed = sum(1 for check in CHECKS if check["passed"])
    result = {
        "probe": "du_cross_arena_dynamic_sufficiency_probe",
        "claim_id": "HC-DU-054",
        "work_id": "N5-RS-P5",
        "checks": CHECKS,
        "checks_passed": passed,
        "checks_total": len(CHECKS),
        "scientific_verdict": "SCOPED_SELECTION_OR_FORMATION_OBSTRUCTION",
        "transfer_verdict": "KNOWN_MATHEMATICS__FULLY_ABSORBED",
        "smallest_missing_arrow": (
            "ANTECEDENT_TO_COMPLETE_ACCESSIBLE_FORMED_INTERFACE_SELECTION"
        ),
        "portfolio_return": "NORTH_STAR_PORTFOLIO_RESET",
        "h_ccr_17": "OPEN_BUT_DORMANT_BEHIND_PHYSICAL_REOPENER",
        "maximum_grade": (
            "SCOPED_CROSS_ARENA_FORMATION_TRANSFER_SEPARATION_AND_ABSORPTION"
        ),
        "not_claimed": [
            "universal record-formation no-go",
            "common native physical mechanism",
            "new factorization theorem",
            "new general-relativistic theorem",
            "new physics",
            "prediction",
            "paper promotion",
            "hardware requirement",
        ],
    }
    ARTIFACT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")

    if passed != len(CHECKS):
        failed = [check["name"] for check in CHECKS if not check["passed"]]
        print(f"FAIL: {passed}/{len(CHECKS)} checks; failed={failed}")
        return 1

    print(
        "CROSS_ARENA_TRANSFER_ABSORBED__FORMATION_SELECTION_OPEN: "
        f"{passed}/{len(CHECKS)} checks"
    )
    print(f"artifact: {ARTIFACT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
