#!/usr/bin/env python3
"""Exact finite controls for HC-DU-138.

The analytic result distinguishes three objects:

1. one actual autonomous evolution;
2. an action envelope generated by a physically typed controller packet; and
3. the response quotient induced by that action envelope.

The probe checks a one-qubit Hamiltonian-control example and a fixed
programmable processor.  It is a regression for the exact proof, not evidence
that nature selects an observer, controller, preparation class, record,
archive, access boundary, or new physical law.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Callable, Hashable, Iterable, Sequence


ROOT = Path(__file__).resolve().parent
ARTIFACT = (
    ROOT
    / "artifacts"
    / "du_physical_action_envelope_compiler_result.json"
)

Matrix = tuple[tuple[complex, ...], ...]
Vector = tuple[complex, ...]

TOLERANCE = 1e-10
CHECKS: list[dict[str, object]] = []


def record(name: str, passed: bool, detail: object) -> None:
    CHECKS.append({"name": name, "passed": bool(passed), "detail": detail})


def close(left: complex, right: complex) -> bool:
    return abs(left - right) <= TOLERANCE


def matrix_close(left: Matrix, right: Matrix) -> bool:
    return (
        len(left) == len(right)
        and all(len(a) == len(b) for a, b in zip(left, right, strict=True))
        and all(
            close(a, b)
            for row_left, row_right in zip(left, right, strict=True)
            for a, b in zip(row_left, row_right, strict=True)
        )
    )


def vector_close(left: Vector, right: Vector) -> bool:
    return len(left) == len(right) and all(
        close(a, b) for a, b in zip(left, right, strict=True)
    )


def identity(size: int) -> Matrix:
    return tuple(
        tuple(complex(int(row == column)) for column in range(size))
        for row in range(size)
    )


def dagger(matrix: Matrix) -> Matrix:
    return tuple(
        tuple(matrix[row][column].conjugate() for row in range(len(matrix)))
        for column in range(len(matrix[0]))
    )


def matrix_multiply(left: Matrix, right: Matrix) -> Matrix:
    return tuple(
        tuple(
            sum(
                left[row][inner] * right[inner][column]
                for inner in range(len(right))
            )
            for column in range(len(right[0]))
        )
        for row in range(len(left))
    )


def matrix_vector(matrix: Matrix, vector: Vector) -> Vector:
    return tuple(
        sum(matrix[row][column] * vector[column] for column in range(len(vector)))
        for row in range(len(matrix))
    )


def scalar_multiply(value: complex, matrix: Matrix) -> Matrix:
    return tuple(tuple(value * entry for entry in row) for row in matrix)


def matrix_subtract(left: Matrix, right: Matrix) -> Matrix:
    return tuple(
        tuple(a - b for a, b in zip(row_left, row_right, strict=True))
        for row_left, row_right in zip(left, right, strict=True)
    )


def commutator(left: Matrix, right: Matrix) -> Matrix:
    return matrix_subtract(
        matrix_multiply(left, right),
        matrix_multiply(right, left),
    )


def flatten(matrix: Matrix) -> list[complex]:
    return [entry for row in matrix for entry in row]


def vector_rank(vectors: Sequence[Sequence[complex]]) -> int:
    """Numerical rank for tiny exact Pauli specimens."""

    if not vectors:
        return 0
    work = [list(vector) for vector in vectors]
    rows = len(work)
    columns = len(work[0])
    rank = 0
    for column in range(columns):
        pivot = next(
            (
                row
                for row in range(rank, rows)
                if abs(work[row][column]) > TOLERANCE
            ),
            None,
        )
        if pivot is None:
            continue
        work[rank], work[pivot] = work[pivot], work[rank]
        pivot_value = work[rank][column]
        work[rank] = [value / pivot_value for value in work[rank]]
        for row in range(rows):
            if row == rank:
                continue
            factor = work[row][column]
            if abs(factor) <= TOLERANCE:
                continue
            work[row] = [
                value - factor * pivot_entry
                for value, pivot_entry in zip(
                    work[row],
                    work[rank],
                    strict=True,
                )
            ]
        rank += 1
        if rank == rows:
            break
    return rank


def lie_closure_dimension(generators: Sequence[Matrix]) -> int:
    basis: list[Matrix] = []

    def add_if_independent(candidate: Matrix) -> bool:
        before = vector_rank([flatten(item) for item in basis])
        after = vector_rank([flatten(item) for item in basis + [candidate]])
        if after > before:
            basis.append(candidate)
            return True
        return False

    for generator in generators:
        add_if_independent(generator)
    changed = True
    while changed:
        changed = False
        snapshot = tuple(basis)
        for left_index, left in enumerate(snapshot):
            for right in snapshot[left_index + 1 :]:
                changed = add_if_independent(commutator(left, right)) or changed
    return len(basis)


def block_diagonal(first: Matrix, second: Matrix) -> Matrix:
    first_size = len(first)
    second_size = len(second)
    result = [
        [0j for _ in range(first_size + second_size)]
        for _ in range(first_size + second_size)
    ]
    for row in range(first_size):
        for column in range(first_size):
            result[row][column] = first[row][column]
    for row in range(second_size):
        for column in range(second_size):
            result[first_size + row][first_size + column] = second[row][column]
    return tuple(tuple(row) for row in result)


def probabilities(vector: Vector) -> tuple[float, ...]:
    return tuple(round(abs(entry) ** 2, 12) for entry in vector)


def response_signature(
    state: Vector,
    actions: Sequence[str],
    action_map: dict[str, Matrix],
) -> tuple[tuple[float, ...], ...]:
    return tuple(
        probabilities(matrix_vector(action_map[action], state))
        for action in actions
    )


def partition(
    domain: Iterable[Hashable],
    classifier: Callable[[Hashable], Hashable],
) -> frozenset[frozenset[Hashable]]:
    cells: dict[Hashable, set[Hashable]] = {}
    for item in domain:
        cells.setdefault(classifier(item), set()).add(item)
    return frozenset(frozenset(cell) for cell in cells.values())


def refines(
    finer: frozenset[frozenset[Hashable]],
    coarser: frozenset[frozenset[Hashable]],
) -> bool:
    return all(any(cell <= large for large in coarser) for cell in finer)


def main() -> int:
    root_two = 2**0.5
    pauli_x: Matrix = ((0j, 1 + 0j), (1 + 0j, 0j))
    pauli_y: Matrix = ((0j, -1j), (1j, 0j))
    pauli_z: Matrix = ((1 + 0j, 0j), (0j, -1 + 0j))
    hadamard: Matrix = (
        (1 / root_two, 1 / root_two),
        (1 / root_two, -1 / root_two),
    )
    one_qubit_identity = identity(2)

    anti_x = scalar_multiply(-1j, pauli_x)
    anti_z = scalar_multiply(-1j, pauli_z)
    z_only_dimension = lie_closure_dimension((anti_z,))
    zx_dimension = lie_closure_dimension((anti_z, anti_x))

    record(
        "drift_only_packet_has_one_dimensional_lie_algebra",
        z_only_dimension == 1,
        z_only_dimension,
    )
    record(
        "adding_one_control_generator_produces_su2",
        zx_dimension == 3,
        zx_dimension,
    )
    record(
        "pauli_commutator_supplies_third_direction",
        vector_rank(
            [
                flatten(pauli_x),
                flatten(pauli_y),
                flatten(pauli_z),
            ]
        )
        == 3,
        "[X,Y,Z] are linearly independent",
    )
    record(
        "same_drift_does_not_select_one_action_envelope",
        z_only_dimension != zx_dimension,
        "both packets have H0=Z; only the admitted control generator differs",
    )

    conjugated_z = matrix_multiply(
        matrix_multiply(hadamard, anti_z),
        dagger(hadamard),
    )
    conjugated_x = matrix_multiply(
        matrix_multiply(hadamard, anti_x),
        dagger(hadamard),
    )
    record(
        "lie_dimension_is_representation_invariant",
        lie_closure_dimension((conjugated_z, conjugated_x)) == zx_dimension,
        "unitary conjugation preserves the generated action algebra",
    )

    processor = block_diagonal(one_qubit_identity, hadamard)
    record(
        "controlled_hadamard_processor_is_unitary",
        matrix_close(
            matrix_multiply(dagger(processor), processor),
            identity(4),
        ),
        "program 0 applies I; program 1 applies H",
    )

    program_zero: Vector = (1 + 0j, 0j)
    program_one: Vector = (0j, 1 + 0j)
    record(
        "exact_program_states_are_orthogonal",
        close(
            sum(
                left.conjugate() * right
                for left, right in zip(
                    program_zero,
                    program_one,
                    strict=True,
                )
            ),
            0j,
        ),
        "<0|1>=0",
    )

    actions = {"I": one_qubit_identity, "H": hadamard}
    support_zero = ("I",)
    support_both = ("I", "H")
    record(
        "singleton_program_support_compiles_singleton_envelope",
        support_zero == ("I",),
        support_zero,
    )
    record(
        "two_program_support_compiles_two_action_envelope",
        set(support_both) == {"I", "H"},
        support_both,
    )
    record(
        "controller_resource_extension_is_monotone",
        set(support_zero) < set(support_both),
        "admitting the second reachable program only enlarges the envelope",
    )
    record(
        "program_dimension_bounds_this_exact_action_family",
        len(support_both) <= len(program_zero),
        "two orthogonal programs in a two-dimensional program register",
    )

    plus: Vector = (1 / root_two, 1 / root_two)
    minus: Vector = (1 / root_two, -1 / root_two)
    record(
        "identity_z_readout_confuses_plus_and_minus",
        response_signature(plus, support_zero, actions)
        == response_signature(minus, support_zero, actions),
        response_signature(plus, support_zero, actions),
    )
    record(
        "hadamard_action_separates_plus_and_minus",
        response_signature(plus, support_both, actions)
        != response_signature(minus, support_both, actions),
        {
            "plus": response_signature(plus, support_both, actions),
            "minus": response_signature(minus, support_both, actions),
        },
    )
    record(
        "hadamard_maps_plus_to_zero",
        vector_close(matrix_vector(hadamard, plus), (1 + 0j, 0j)),
        probabilities(matrix_vector(hadamard, plus)),
    )
    record(
        "hadamard_maps_minus_to_one",
        vector_close(matrix_vector(hadamard, minus), (0j, 1 + 0j)),
        probabilities(matrix_vector(hadamard, minus)),
    )

    state_domain = ("plus", "minus")
    state_vectors = {"plus": plus, "minus": minus}
    coarse = partition(
        state_domain,
        lambda name: response_signature(
            state_vectors[name],
            support_zero,
            actions,
        ),
    )
    fine = partition(
        state_domain,
        lambda name: response_signature(
            state_vectors[name],
            support_both,
            actions,
        ),
    )
    record(
        "larger_physical_action_envelope_refines_response_quotient",
        refines(fine, coarse) and len(coarse) == 1 and len(fine) == 2,
        {"coarse_cells": len(coarse), "fine_cells": len(fine)},
    )

    packet_domain = (
        ("same_processor", "actual_program_zero", frozenset({"I"})),
        ("same_processor", "actual_program_zero", frozenset({"I", "H"})),
    )
    processor_only = lambda item: item[0]
    actual_history = lambda item: (item[0], item[1])
    envelope = lambda item: item[2]
    record(
        "processor_alone_does_not_select_action_envelope",
        len({envelope(item) for item in packet_domain}) == 2
        and len({processor_only(item) for item in packet_domain}) == 1,
        "same processor, different admitted preparation supports",
    )
    record(
        "one_actual_program_history_does_not_select_counterfactual_envelope",
        len({envelope(item) for item in packet_domain}) == 2
        and len({actual_history(item) for item in packet_domain}) == 1,
        "the actual program-zero execution is identical in both packets",
    )
    record(
        "complete_controller_packet_selects_its_envelope",
        all(
            envelope(item)
            == (
                frozenset({"I"})
                if len(item[2]) == 1
                else frozenset({"I", "H"})
            )
            for item in packet_domain
        ),
        "processor plus reachable-program support determines the action set",
    )

    checks = {item["name"]: item["passed"] for item in CHECKS}
    assert all(checks.values())
    artifact = {
        "claim_id": "HC-DU-138",
        "status": "PASS",
        "checks_passed": len(checks),
        "checks_total": len(checks),
        "checks": checks,
        "hamiltonian_control": {
            "shared_drift": "Z",
            "drift_only_lie_dimension": z_only_dimension,
            "drift_plus_x_lie_dimension": zx_dimension,
        },
        "programmable_controller": {
            "processor": "controlled-H",
            "program_support_small": ["I"],
            "program_support_large": ["I", "H"],
            "program_dimension": 2,
            "small_response_cells": len(coarse),
            "large_response_cells": len(fine),
        },
        "formal_boundary": {
            "conditional_selector": (
                "A fixed physical controller, reachable preparation/resource "
                "class, readout, and horizon compile an action envelope and "
                "therefore a response quotient."
            ),
            "nonselection": (
                "The drift/source law, processor alone, and one actual program "
                "history do not determine the counterfactual preparation class."
            ),
            "monotonicity": (
                "Enlarging the admitted physical controller resources enlarges "
                "the action envelope and can strictly refine response classes."
            ),
        },
        "non_claims": [
            "not a new quantum-control or programmable-processor theorem",
            "not a selected observer, controller, preparation class, or archive in nature",
            "not a universal impossibility of deriving counterfactual tasks from physics",
            "not a record ontology, physical remainder, prediction, law, or new physics",
        ],
    }
    ARTIFACT.write_text(
        json.dumps(artifact, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(f"PASS: {len(checks)}/{len(checks)} exact finite checks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
