#!/usr/bin/env python3
"""Wild-frontier council swing: Fisher-selected causal growth and a count scale.

This is a deliberately minimal construction/kill, not a cosmology.

At a finite causal set C, a new maximal event is generated by independently
proposing a direct link to each existing event with probability p and then
taking the transitive closure.  For constant p this is the transitive-
percolation member of classical sequential growth.  The physical transition
outcomes are down-sets of C.

The Bernoulli link family has logit coordinate g and Fisher metric

    F_raw = n p(1-p).

If one inserts the relation-favouring local source potential

    S(g; C) = -E[number of proposed direct links] = -n p,

then KL/Fisher natural-gradient descent gives

    dg / d log N = -F_raw^{-1} dS/dg = 1.

Consequently N_* = N exp(-g) is invariant and, conditional on an atom length
ell_0 and recovered dimension d, ell_* = ell_0 N_*^(1/d).  No N_* target is
present in the update.

The cheap kill is full discrete general covariance.  A p that runs with birth
cardinality gives different path probabilities to different natural labelings
of the same three-element causet, even though every statewise transition law
is invariant under relabeling.  Constant p passes the same exact test.

The probe also constructs the *expected* Fisher contribution of each physical
down-set outcome.  That is a genuine Fisher-information decomposition, unlike
the observed residual-energy object in SWING-DU-PHY-02 Track B.  It is useful
as a downstream diagnostic, but the killed count-running law cannot yet make
it a physical DU observable.
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import Any, Callable

from conditional_candidate_harness import (
    SCHEMA_VERSION,
    comparison_receipt,
    write_candidate_artifact,
)


ARTIFACT_PATH = (
    Path(__file__).resolve().parent
    / "artifacts"
    / "du_wild_frontier_fisher_csg_scale_bridge_probe_result.json"
)


def logistic(g: float) -> float:
    if g >= 0.0:
        z = math.exp(-g)
        return 1.0 / (1.0 + z)
    z = math.exp(g)
    return z / (1.0 + z)


def map_mask(mask: int, old_to_new: tuple[int, ...]) -> int:
    mapped = 0
    for old, new in enumerate(old_to_new):
        if mask & (1 << old):
            mapped |= 1 << new
    return mapped


def relabel_ancestors(
    ancestors: tuple[int, ...], old_to_new: tuple[int, ...]
) -> tuple[int, ...]:
    relabeled = [0] * len(ancestors)
    for old, new in enumerate(old_to_new):
        relabeled[new] = map_mask(ancestors[old], old_to_new)
    return tuple(relabeled)


def transition_distribution(
    ancestors: tuple[int, ...], p: float
) -> dict[int, dict[str, float]]:
    """Aggregate Bernoulli direct-link histories by their causal down-closure."""

    n = len(ancestors)
    outcomes: dict[int, dict[str, float]] = {}
    for raw_mask in range(1 << n):
        direct_count = raw_mask.bit_count()
        probability = (p**direct_count) * ((1.0 - p) ** (n - direct_count))
        score = direct_count - n * p  # d log P(raw history) / dg
        closure = 0
        for event in range(n):
            if raw_mask & (1 << event):
                closure |= ancestors[event] | (1 << event)
        row = outcomes.setdefault(
            closure,
            {
                "probability": 0.0,
                "probability_derivative_g": 0.0,
            },
        )
        row["probability"] += probability
        row["probability_derivative_g"] += probability * score

    for row in outcomes.values():
        probability = row["probability"]
        outcome_score = row["probability_derivative_g"] / probability
        row["score_g"] = outcome_score
        row["fisher_contribution"] = probability * outcome_score * outcome_score
    return outcomes


def outcome_summary(
    ancestors: tuple[int, ...], p: float
) -> dict[str, Any]:
    outcomes = transition_distribution(ancestors, p)
    total_probability = sum(row["probability"] for row in outcomes.values())
    fisher_observed = sum(
        row["fisher_contribution"] for row in outcomes.values()
    )
    n = len(ancestors)
    fisher_raw = n * p * (1.0 - p)
    if fisher_observed > 0.0:
        influence = {
            str(mask): row["fisher_contribution"] / fisher_observed
            for mask, row in sorted(outcomes.items())
        }
    else:
        influence = {}
    return {
        "event_count": n,
        "p": p,
        "outcome_count": len(outcomes),
        "total_probability": total_probability,
        "raw_link_fisher": fisher_raw,
        "downset_outcome_fisher": fisher_observed,
        "data_processing_ratio": (
            fisher_observed / fisher_raw if fisher_raw > 0.0 else None
        ),
        "normalized_expected_fisher_contributions": influence,
        "outcomes": {
            str(mask): row for mask, row in sorted(outcomes.items())
        },
    }


def relabeling_test(
    ancestors: tuple[int, ...], p: float
) -> dict[str, Any]:
    baseline = transition_distribution(ancestors, p)
    permutations = (
        (2, 0, 3, 1),
        (1, 3, 0, 2),
        (3, 2, 1, 0),
    )
    maximum_probability_error = 0.0
    maximum_fisher_contribution_error = 0.0
    for permutation in permutations:
        relabeled = relabel_ancestors(ancestors, permutation)
        transformed = transition_distribution(relabeled, p)
        for old_mask, row in baseline.items():
            new_mask = map_mask(old_mask, permutation)
            transformed_row = transformed[new_mask]
            maximum_probability_error = max(
                maximum_probability_error,
                abs(row["probability"] - transformed_row["probability"]),
            )
            maximum_fisher_contribution_error = max(
                maximum_fisher_contribution_error,
                abs(
                    row["fisher_contribution"]
                    - transformed_row["fisher_contribution"]
                ),
            )
    return {
        "permutations": [list(item) for item in permutations],
        "maximum_probability_error": maximum_probability_error,
        "maximum_fisher_contribution_error": (
            maximum_fisher_contribution_error
        ),
        "reading": (
            "Each fixed-state transition law and its Fisher contributions "
            "are exactly equivariant under event relabeling."
        ),
    }


def induced_ancestors(
    final_ancestors: tuple[int, ...], born: tuple[int, ...]
) -> tuple[int, ...]:
    old_to_current = {old: current for current, old in enumerate(born)}
    induced: list[int] = []
    for old in born:
        mask = 0
        for ancestor_old in born:
            if final_ancestors[old] & (1 << ancestor_old):
                mask |= 1 << old_to_current[ancestor_old]
        induced.append(mask)
    return tuple(induced)


def target_past_mask(
    final_ancestors: tuple[int, ...],
    born: tuple[int, ...],
    new_event: int,
) -> int:
    mask = 0
    for current, old in enumerate(born):
        if final_ancestors[new_event] & (1 << old):
            mask |= 1 << current
    return mask


def path_probability(
    final_ancestors: tuple[int, ...],
    natural_order: tuple[int, ...],
    p_at_existing_count: Callable[[int], float],
) -> float:
    probability = 1.0
    for existing_count in range(len(natural_order)):
        born = natural_order[:existing_count]
        new_event = natural_order[existing_count]
        current = induced_ancestors(final_ancestors, born)
        target = target_past_mask(
            final_ancestors, born, new_event
        )
        transition = transition_distribution(
            current, p_at_existing_count(existing_count)
        )
        probability *= transition[target]["probability"]
    return probability


def covariance_test() -> dict[str, Any]:
    # Final causet: a<c, with b incomparable to both.
    final_ancestors = (0, 0, 1 << 0)
    natural_orders = (
        (0, 1, 2),
        (1, 0, 2),
        (0, 2, 1),
    )
    constant_p = 0.27
    constant_probabilities = [
        path_probability(
            final_ancestors, order, lambda _n: constant_p
        )
        for order in natural_orders
    ]

    g_reference = -math.log(16.0)

    def running_p(existing_count: int) -> float:
        count_coordinate = existing_count + 1.0
        return logistic(g_reference + math.log(count_coordinate))

    running_probabilities = [
        path_probability(final_ancestors, order, running_p)
        for order in natural_orders
    ]
    constant_spread = max(constant_probabilities) - min(
        constant_probabilities
    )
    running_spread = max(running_probabilities) - min(
        running_probabilities
    )
    running_ratio = max(running_probabilities) / min(
        running_probabilities
    )
    return {
        "final_causet": "three events with a<c and b isolated",
        "natural_orders": [list(order) for order in natural_orders],
        "constant_p": {
            "p": constant_p,
            "path_probabilities": constant_probabilities,
            "absolute_spread": constant_spread,
            "classification": "DISCRETE_GENERAL_COVARIANCE_PASSES_THIS_NULL",
        },
        "count_running_p": {
            "g_reference": g_reference,
            "law": "g(N)=g_reference+log(N), p(N)=logistic(g(N))",
            "path_probabilities": running_probabilities,
            "absolute_spread": running_spread,
            "maximum_to_minimum_ratio": running_ratio,
            "classification": "DISCRETE_GENERAL_COVARIANCE_FAIL",
        },
        "reading": (
            "Statewise relabeling invariance is weaker than path independence. "
            "The cardinality-running coupling makes birth labels observable."
        ),
    }


def fisher_natural_flow_test() -> dict[str, Any]:
    rows = []
    maximum_beta_error = 0.0
    maximum_reparameterization_error = 0.0
    n = 4
    for g in (-2.0, -0.6, 0.0, 0.8, 2.0):
        p = logistic(g)
        fisher_g = n * p * (1.0 - p)
        # Inserted source potential S=-E[m]=-n p.
        derivative_s_g = -fisher_g
        beta_g = -derivative_s_g / fisher_g

        # h=sinh(g): test natural-gradient covariance explicitly.
        dh_dg = math.cosh(g)
        fisher_h = fisher_g / (dh_dg * dh_dg)
        derivative_s_h = derivative_s_g / dh_dg
        beta_h = -derivative_s_h / fisher_h
        chain_rule_beta_h = dh_dg * beta_g

        maximum_beta_error = max(maximum_beta_error, abs(beta_g - 1.0))
        maximum_reparameterization_error = max(
            maximum_reparameterization_error,
            abs(beta_h - chain_rule_beta_h),
        )
        rows.append(
            {
                "g": g,
                "p": p,
                "fisher_g": fisher_g,
                "dS_dg": derivative_s_g,
                "natural_beta_g": beta_g,
                "h": math.sinh(g),
                "natural_beta_h": beta_h,
                "chain_rule_beta_h": chain_rule_beta_h,
            }
        )
    return {
        "source_potential": "S(g;C)=-E[number of direct links]=-n p(g)",
        "mobility_principle": (
            "The local KL Hessian supplies Fisher mobility on the Bernoulli "
            "transition family."
        ),
        "rows": rows,
        "maximum_beta_error_from_one": maximum_beta_error,
        "maximum_reparameterization_error": (
            maximum_reparameterization_error
        ),
        "inserted_choices": [
            "the Bernoulli direct-link microhistory",
            "KL as the local path cost",
            "the sign S=-E[m], favouring relation creation",
            "log cardinality as the flow parameter",
            "unit coefficient in that flow parameter",
        ],
    }


def transmuted_scale_test() -> dict[str, Any]:
    count_grid = (1.0, 2.0, 4.0, 8.0, 16.0, 32.0, 64.0, 128.0)
    fixtures = []
    maximum_invariant_relative_error = 0.0
    for target_count in (4.0, 16.0, 64.0):
        g_reference = -math.log(target_count)
        rows = []
        invariants = []
        for count in count_grid:
            g = g_reference + math.log(count)
            invariant = count * math.exp(-g)
            invariants.append(invariant)
            rows.append(
                {
                    "count_coordinate": count,
                    "g": g,
                    "p": logistic(g),
                    "N_exp_minus_g": invariant,
                }
            )
        maximum_invariant_relative_error = max(
            maximum_invariant_relative_error,
            max(abs(value - target_count) / target_count for value in invariants),
        )
        fixtures.append(
            {
                "g_reference": g_reference,
                "generated_count_scale": target_count,
                "crossover_p_equals_one_half_at_N": target_count,
                "ell_star_over_ell_atom_if_d_equals_4": target_count ** 0.25,
                "rows": rows,
            }
        )
    return {
        "flow": "dg/dlogN=1",
        "rg_invariant": "N_*=N exp(-g(N))",
        "unit_map": "ell_*=ell_atom N_*^(1/d_recovered)",
        "fixtures": fixtures,
        "maximum_invariant_relative_error": maximum_invariant_relative_error,
        "interpretation": (
            "A count hierarchy can be transmuted from a dimensionless initial "
            "coupling without inserting N_* into the update. Its value remains "
            "an initial-condition output, and a dimensional length still imports "
            "ell_atom and requires recovered d."
        ),
    }


def main() -> None:
    # Four-event diamond: 0<1, 0<2, and 1,2<3.
    diamond = (0, 1 << 0, 1 << 0, (1 << 0) | (1 << 1) | (1 << 2))
    antichain = (0, 0, 0, 0)
    chain = (0, 1, 3, 7)
    p = 0.31

    diamond_outcomes = outcome_summary(diamond, p)
    antichain_outcomes = outcome_summary(antichain, p)
    chain_outcomes = outcome_summary(chain, p)
    relabeling = relabeling_test(diamond, p)
    natural_flow = fisher_natural_flow_test()
    scale = transmuted_scale_test()
    covariance = covariance_test()

    fisher_weights = list(
        diamond_outcomes[
            "normalized_expected_fisher_contributions"
        ].values()
    )
    checks = [
        {
            "name": "physical down-set transition probabilities normalize",
            "pass": all(
                abs(item["total_probability"] - 1.0) < 2.0e-14
                for item in (
                    diamond_outcomes,
                    antichain_outcomes,
                    chain_outcomes,
                )
            ),
        },
        {
            "name": "expected down-set Fisher contributions are nonnegative and normalize",
            "pass": (
                min(fisher_weights) >= 0.0
                and abs(sum(fisher_weights) - 1.0) < 2.0e-14
            ),
        },
        {
            "name": "fixed-state transition law is exactly relabeling equivariant",
            "pass": (
                relabeling["maximum_probability_error"] < 2.0e-14
                and relabeling[
                    "maximum_fisher_contribution_error"
                ]
                < 2.0e-14
            ),
        },
        {
            "name": "causal closure cannot increase Fisher information",
            "pass": all(
                item["downset_outcome_fisher"]
                <= item["raw_link_fisher"] + 2.0e-14
                for item in (
                    diamond_outcomes,
                    antichain_outcomes,
                    chain_outcomes,
                )
            ),
        },
        {
            "name": "antichain closure retains the complete raw-link Fisher information",
            "pass": abs(
                antichain_outcomes["data_processing_ratio"] - 1.0
            )
            < 2.0e-14,
        },
        {
            "name": "nontrivial causal closure loses some raw-link Fisher information",
            "pass": (
                0.0 < diamond_outcomes["data_processing_ratio"] < 1.0
                and 0.0 < chain_outcomes["data_processing_ratio"] < 1.0
            ),
        },
        {
            "name": "KL/Fisher natural descent of the inserted source potential gives beta_g=1",
            "pass": natural_flow["maximum_beta_error_from_one"] < 2.0e-14,
        },
        {
            "name": "the natural-gradient flow is covariant under h=sinh(g)",
            "pass": natural_flow[
                "maximum_reparameterization_error"
            ]
            < 2.0e-13,
        },
        {
            "name": "N exp(-g) is invariant along the analytic count flow",
            "pass": scale["maximum_invariant_relative_error"] < 2.0e-14,
        },
        {
            "name": "constant-p transitive percolation passes the three-event path-independence null",
            "pass": covariance["constant_p"]["absolute_spread"] < 2.0e-14,
        },
        {
            "name": "cardinality-running p fails the same path-independence null",
            "pass": (
                covariance["count_running_p"]["absolute_spread"] > 1.0e-5
                and covariance["count_running_p"][
                    "maximum_to_minimum_ratio"
                ]
                > 1.05
            ),
        },
        {
            "name": "no Lambda, H0, cosmological age, target geometry, or target concentration enters the probe",
            "pass": True,
        },
    ]
    passed = sum(bool(item["pass"]) for item in checks)

    candidate = {
        "schema_version": SCHEMA_VERSION,
        "candidate_id": "DU-WILD-FISHER-CSG-SCALE-BRIDGE",
        "track": (
            "Science Council wild-frontier next actions / HC-DU-011 + HC-DU-022"
        ),
        "question": (
            "Can a minimal order-first causal growth law select Fisher mobility, "
            "transmute a dimensionless coupling into a count scale, and generate "
            "a downstream influence object without violating discrete general "
            "covariance?"
        ),
        "warrants": [
            "DERIVED",
            "CONDITIONALLY_ENTAILED",
            "CONSTRUCTIVELY_REALIZED",
            "STRUCTURAL_ANALOGY",
        ],
        "assumptions": [
            {
                "id": "A1",
                "statement": (
                    "Bernoulli direct-link proposals followed by transitive "
                    "closure form the order-first microhistory."
                ),
                "status": "STANDARD",
                "role": (
                    "Supplies a transitive-percolation growth family and physical "
                    "down-set outcomes."
                ),
            },
            {
                "id": "A2",
                "statement": (
                    "Local relative entropy is the path cost on the transition "
                    "statistical manifold."
                ),
                "status": "CONDITIONAL_POSIT",
                "role": "Its Hessian selects the Fisher mobility.",
            },
            {
                "id": "A3",
                "statement": (
                    "The source potential is minus expected direct-link count."
                ),
                "status": "CONDITIONAL_POSIT",
                "role": (
                    "Chooses the sign that favours relation creation and yields "
                    "the tested marginal natural flow."
                ),
            },
            {
                "id": "A4",
                "statement": (
                    "Log causal cardinality is the candidate flow parameter."
                ),
                "status": "CONDITIONAL_POSIT",
                "role": (
                    "Makes the analytic beta law generate a count hierarchy and "
                    "is the choice attacked by the path-covariance kill."
                ),
            },
            {
                "id": "A5",
                "statement": (
                    "A microscopic atom length and recovered dimension would map "
                    "a count hierarchy to a dimensional length."
                ),
                "status": "PROJECT_NATIVE",
                "role": (
                    "Keeps the unit map explicit without claiming that either "
                    "input has been derived here."
                ),
            },
        ],
        "free_choices": [
            {
                "id": "C1",
                "choice": "Use one Bernoulli probability for every potential direct link.",
                "why_not_forced": (
                    "More general classical sequential growth laws have multiple "
                    "couplings and precursor dependence."
                ),
                "sensitivity_test": (
                    "Compare antichain, diamond, and chain causal closures and "
                    "retain the data-processing loss."
                ),
            },
            {
                "id": "C2",
                "choice": "Use S=-E[m] and unit natural-flow normalization.",
                "why_not_forced": (
                    "The sign, local source functional, and time normalization "
                    "are not selected by the causal order alone."
                ),
                "sensitivity_test": (
                    "Expose the choices and check coordinate covariance under "
                    "h=sinh(g); do not interpret the hierarchy value as predicted."
                ),
            },
            {
                "id": "C3",
                "choice": "Use illustrative initial couplings generating N*=4,16,64.",
                "why_not_forced": (
                    "No physical law in this probe selects the initial coupling."
                ),
                "sensitivity_test": (
                    "Require N exp(-g) to stay invariant for all three values and "
                    "report their different length ratios."
                ),
            },
            {
                "id": "C4",
                "choice": (
                    "Use the smallest three-event causet with inequivalent natural "
                    "birth paths as the covariance kill."
                ),
                "why_not_forced": (
                    "Many larger causets can test the same path-independence burden."
                ),
                "sensitivity_test": (
                    "Require constant-p transitive percolation to pass the identical "
                    "fixture while count-running p fails."
                ),
            },
        ],
        "equations": [
            "g=log[p/(1-p)]",
            "F_raw=n p(1-p)",
            "S(g;C)=-E[m]=-n p",
            "dg/dlogN=-F_raw^-1 dS/dg=1",
            "N_*=N exp[-g(N)]",
            "ell_*=ell_atom N_*^(1/d_recovered)",
            "I_y=q_y (d log q_y/dg)^2",
            "F_downset=sum_y I_y <= F_raw",
        ],
        "observables": [
            "physical down-set transition probabilities",
            "raw-link and down-set Fisher information",
            "normalized expected Fisher contribution by physical outcome",
            "statewise relabeling errors",
            "natural-gradient beta in g and h=sinh(g)",
            "N exp(-g) along the count flow",
            "path probability across natural labelings",
        ],
        "comparators": [
            "antichain versus diamond versus chain causal closure",
            "raw-link Fisher versus physical down-set Fisher",
            "constant-p versus cardinality-running transitive percolation",
            "statewise relabeling equivariance versus full path covariance",
        ],
        "null_models": [
            "an antichain closure preserves every raw direct-link history",
            "constant-p transitive percolation assigns equal path weight on the three-event fixture",
            "a coordinate change h=sinh(g) changes components but not the natural-gradient path",
        ],
        "falsifiers": [
            "physical transition probabilities or normalized Fisher contributions fail to normalize",
            "event relabeling changes a fixed-state transition probability",
            "causal closure increases Fisher information",
            "N exp(-g) is not invariant under the analytic flow",
            "different natural labelings receive unequal path probability",
            "the claimed hierarchy requires inserting N_* into the update",
        ],
        "stop_conditions": [
            "Stop the exact feedback law if one natural-labeling counterexample exists.",
            "Do not call the transmuted count a physical length without ell_atom and recovered dimension.",
            "Do not treat expected transition Fisher contribution as Track B observed residual energy.",
            "Do not infer a Lambda identity, value, banked claim, or prediction from the construction.",
            "Local failure remains formalization-scoped rather than a concept kill.",
        ],
        "concept": {
            "concept_id": "CONCEPT-DU-001",
            "invariant": (
                "A live DU mechanism generates nonuniform effective influence "
                "through its own higher-order dynamics rather than fitting a target."
            ),
            "formalization_id": "FISHER-CSG-COUNT-RUNNING-SCALE-BRIDGE",
            "failure_scope": "FORMALIZATION",
        },
        "result": {
            "claim": (
                "The fixed-state transition family constructs Fisher mobility, "
                "an invariant count-scale skeleton, and a genuine expected-Fisher "
                "influence profile, but direct cardinality running makes completed-"
                "causet path probabilities depend on natural labeling."
            ),
            "grade": (
                "CONSTRUCTIVE-SKELETON-FOUND / NAIVE-COUNT-RUNNING-KILLED"
            ),
            "admission": "FORMALIZATION_FALSIFIED",
            "remaining_uncertainty": (
                "A covariant fixed-coupling renormalization or physical coupling-"
                "record extension may evade the kill; geometry recovery, a stable "
                "gap, units, response/noise completion, and cosmology remain open."
            ),
            "checks": checks,
        },
    }

    payload = {
        "probe": "du_wild_frontier_fisher_csg_scale_bridge_probe",
        "contested_finding": (
            "The HC-DU-011 + HC-DU-022 bridge is wholly unbuilt: no coherent "
            "order-first law can yet select a mobility, generate a count scale, "
            "and make influence a downstream response object."
        ),
        "construction": {
            "micro_law": (
                "Independent Bernoulli direct-link proposals followed by "
                "causal transitive closure."
            ),
            "physical_outcomes": "down-sets used as the past of a new maximal event",
            "mobility": "Fisher metric from local KL on the transition family",
            "source_potential": "-expected direct-link count",
            "count_flow": "dg/dlogN=1",
            "generated_scale": "N_*=N exp(-g), ell_*=ell_atom N_*^(1/d)",
            "downstream_influence": (
                "normalized expected Fisher contributions of physical down-set outcomes"
            ),
        },
        "inserted_choices": natural_flow["inserted_choices"]
        + [
            "the initial dimensionless coupling g_reference",
            "the microscopic unit ell_atom",
            "the dimension used in the units map",
            "treating raw direct-link proposals as physical microhistory",
        ],
        "outcome_fisher": {
            "diamond": diamond_outcomes,
            "antichain": antichain_outcomes,
            "chain": chain_outcomes,
            "relabeling": relabeling,
            "reading": (
                "Causal closure is a data-processing map: order structure "
                "changes both total observable Fisher response and its "
                "influence allocation without fitting a target profile."
            ),
        },
        "fisher_natural_flow": natural_flow,
        "count_scale": scale,
        "discrete_general_covariance_kill": covariance,
        "checks": checks,
        "checks_passed": passed,
        "checks_total": len(checks),
        "verdict": (
            "CONSTRUCTIVE-SKELETON-FOUND / NAIVE-COUNT-RUNNING-KILLED. "
            "KL/Fisher supplies a coordinate-covariant mobility, a dimensionless "
            "initial coupling transmutates into an invariant count scale, and "
            "the transition law supplies a genuine expected-Fisher influence "
            "profile. But letting the coupling run with birth cardinality makes "
            "path probabilities depend on natural labeling, so this exact "
            "feedback law is not an admissible covariant causal growth law. "
            "No physical memory scale, geometry recovery, Lambda identity, "
            "claim, or prediction is earned."
        ),
        "cheap_kill": (
            "Enumerate natural labelings of the three-event causet a<c with b "
            "isolated. Any candidate feedback must assign them equal total "
            "path probability. The count-running fixture fails."
        ),
        "scope": {
            "earned": [
                "an algebraically coherent statewise order/Fisher/scale skeleton",
                "a true expected-Fisher transition influence decomposition",
                "an exact obstruction to naive birth-count running",
            ],
            "not_earned": [
                "full classical-sequential-growth covariance for the feedback law",
                "a selected initial coupling or hierarchy",
                "manifoldlike geometry or recovered dimension",
                "a unit-bearing physical memory response",
                "a Bianconi mobility selection",
                "a cosmological observable, Lambda value, banked claim, or seed",
            ],
        },
    }
    receipt = comparison_receipt(candidate)
    if receipt["contract_status"] != "COMPLETE":
        raise RuntimeError(
            f"incomplete candidate contract: {receipt['contract_errors']}"
        )
    write_candidate_artifact(ARTIFACT_PATH, candidate, payload)

    print("WILD-FRONTIER FISHER/CSG/SCALE BRIDGE")
    for check in checks:
        print(f"{'PASS' if check['pass'] else 'FAIL'}  {check['name']}")
    print(f"{passed}/{len(checks)} checks pass")
    print(
        "VERDICT: CONSTRUCTIVE-SKELETON-FOUND / "
        "NAIVE-COUNT-RUNNING-KILLED"
    )
    print(f"contract: {receipt['contract_status']} (not scientific endorsement)")
    print(f"artifact: {ARTIFACT_PATH}")
    if passed != len(checks):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
